---
- hosts: workstation

  tasks:
    - name: install Karabiner
      mac_pkg: pkg_name=org.pqrs.driver.Karabiner pkg_version=10.18.0
               url=https://pqrs.org/osx/karabiner/files/Karabiner-10.18.0.dmg
               archive_type=dmg archive_path='Karabiner.pkg' creates=Karabiner.app
      sudo: yes
