---
- hosts: workstation

  tasks:
    - name: get oh-my-zsh script
      get_url: url=http://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh dest=/tmp/oh-my-zsh.sh

    - name: change file permission to be executable
      file: mode=u+rwx path=/tmp/oh-my-zsh.sh

    - name: install zsh
      script: /tmp/oh-my-zsh.sh creates="{{ ansible_user_dir }}/.oh-my-zsh"
