---
- hosts: workstation

  tasks:
    - name: install vlc
      mac_pkg: pkg_type=app
               url=http://get.videolan.org/vlc/2.2.2/macosx/vlc-2.2.2.dmg
               archive_type=dmg archive_path=VLC.app
      sudo: yes
